"""Pack the reconstructed mesh into a single JS file for viewer/reconstruction.html.

The viewer must open from file:// with no build step and no external assets
(CLAUDE.md), and browsers refuse XHR/fetch on file://, so -- exactly like the
IBR manifests -- the model is embedded as a JS global: a glTF 2.0 binary
(GLB) encoded base64. To keep it browser-sized the texture is downscaled
(TEX px) and JPEG-compressed, and per-corner UVs are welded per
(vertex, uv) pair.

  python3 usdz_to_viewer_js.py <mesh.usdz> <out.js> [tex px]
"""
import sys, os, json, struct, base64, zipfile, tempfile, shutil
import numpy as np, cv2
from pxr import Usd, UsdGeom

src, dst = sys.argv[1], sys.argv[2]
TEX = int(sys.argv[3]) if len(sys.argv) > 3 else 2048

work = tempfile.mkdtemp()
with zipfile.ZipFile(src) as z:
    z.extractall(work)
usdc = [os.path.join(r, f) for r, _, fs in os.walk(work) for f in fs if f.endswith('.usdc')][0]
stage = Usd.Stage.Open(usdc)
mesh = next(p for p in stage.Traverse() if p.IsA(UsdGeom.Mesh))
m = UsdGeom.Mesh(mesh)
P = np.array(m.GetPointsAttr().Get(), dtype=np.float32)
F = np.array(m.GetFaceVertexIndicesAttr().Get()).reshape(-1, 3)
st = UsdGeom.PrimvarsAPI(mesh).GetPrimvar('st')
uv = np.array(st.Get(), dtype=np.float32)
uvi = np.array(st.GetIndices()).reshape(-1, 3)
nrm = m.GetNormalsAttr().Get()
N = np.array(nrm, dtype=np.float32).reshape(-1, 3) if nrm is not None else None

# weld corners by (vertex, uv) pair
pair = F.ravel().astype(np.int64) * len(uv) + uvi.ravel()
uniq, inv = np.unique(pair, return_inverse=True)
vid, tid = uniq // len(uv), uniq % len(uv)
pos = P[vid]
tex = uv[tid].copy()
tex[:, 1] = 1 - tex[:, 1]                     # glTF: v origin top-left
if N is not None and len(N) == len(F) * 3:
    nn = np.zeros((len(uniq), 3), np.float32)
    np.add.at(nn, inv, N)
    nn /= np.linalg.norm(nn, axis=1, keepdims=True) + 1e-9
else:
    nn = None
idx = inv.astype(np.uint32)
print(f'faces {len(F):,}  welded vertices {len(uniq):,}')

# texture
tp = [os.path.join(r, f) for r, _, fs in os.walk(work) for f in fs if f.endswith('_tex0.png')][0]
im = cv2.imread(tp)
h, w = im.shape[:2]
scale = TEX / max(h, w)
im = cv2.resize(im, (int(w * scale), int(h * scale)), interpolation=cv2.INTER_AREA)
ok, jpg = cv2.imencode('.jpg', im, [cv2.IMWRITE_JPEG_QUALITY, 88])
jpg = jpg.tobytes()
print(f'texture {im.shape[1]}x{im.shape[0]} jpeg {len(jpg)/1e6:.1f} MB')

def pad4(b, fill=b'\x00'):
    return b + fill * ((4 - len(b) % 4) % 4)

chunks, views, accessors = [], [], []
def add(data, target, ctype, count, atype, mn=None, mx=None):
    off = sum(len(c) for c in chunks)
    chunks.append(pad4(data))
    views.append({'buffer': 0, 'byteOffset': off, 'byteLength': len(data), **({'target': target} if target else {})})
    acc = {'bufferView': len(views) - 1, 'componentType': ctype, 'count': count, 'type': atype}
    if mn is not None:
        acc['min'], acc['max'] = mn, mx
    accessors.append(acc)
    return len(accessors) - 1

a_pos = add(pos.tobytes(), 34962, 5126, len(pos), 'VEC3', pos.min(0).tolist(), pos.max(0).tolist())
a_uv = add(tex.astype(np.float32).tobytes(), 34962, 5126, len(tex), 'VEC2')
attrs = {'POSITION': a_pos, 'TEXCOORD_0': a_uv}
if nn is not None:
    attrs['NORMAL'] = add(nn.tobytes(), 34962, 5126, len(nn), 'VEC3')
a_idx = add(idx.tobytes(), 34963, 5125, len(idx), 'SCALAR')
img_off = sum(len(c) for c in chunks)
chunks.append(pad4(jpg))
views.append({'buffer': 0, 'byteOffset': img_off, 'byteLength': len(jpg)})
bin_blob = b''.join(chunks)

gltf = {
    'asset': {'version': '2.0', 'generator': 'usdz_to_viewer_js.py'},
    'scene': 0, 'scenes': [{'nodes': [0]}],
    'nodes': [{'mesh': 0}],
    'meshes': [{'primitives': [{'attributes': attrs, 'indices': a_idx, 'material': 0}]}],
    'materials': [{'pbrMetallicRoughness': {'baseColorTexture': {'index': 0}, 'metallicFactor': 0.0, 'roughnessFactor': 0.9},
                   'doubleSided': True}],
    'textures': [{'source': 0, 'sampler': 0}],
    'samplers': [{'magFilter': 9729, 'minFilter': 9987, 'wrapS': 33071, 'wrapT': 33071}],
    'images': [{'bufferView': len(views) - 1, 'mimeType': 'image/jpeg'}],
    'buffers': [{'byteLength': len(bin_blob)}],
    'bufferViews': views, 'accessors': accessors,
}
jb = pad4(json.dumps(gltf, separators=(',', ':')).encode(), b' ')
glb = b'glTF' + struct.pack('<II', 2, 12 + 8 + len(jb) + 8 + len(bin_blob)) \
    + struct.pack('<I', len(jb)) + b'JSON' + jb + struct.pack('<I', len(bin_blob)) + b'BIN\x00' + bin_blob
b64 = base64.b64encode(glb).decode()
with open(dst, 'w') as f:
    f.write('// Generated by recon/objectcapture/usdz_to_viewer_js.py -- do not edit.\n')
    f.write(f'// {os.path.basename(src)}: {len(F):,} faces, texture {im.shape[1]}x{im.shape[0]}.\n')
    f.write('window.SALA_RECON_GLB = "data:model/gltf-binary;base64,' + b64 + '";\n')
print(f'wrote {dst}: glb {len(glb)/1e6:.1f} MB, js {os.path.getsize(dst)/1e6:.1f} MB')
shutil.rmtree(work)
