// Generated by run_pipeline.py -- do not edit.
window.SALA_VERSIONS = {
  "versions": [
    {
      "name": "salathai_version1",
      "label": "Sala Thai Version1",
      "manifest": "manifest_salathai_version1.js",
      "n_captured": 206,
      "n_synthesized": 410,
      "n_frames": 616
    }
  ]
};
