#!/usr/bin/env python3
"""Stage 5: order the frames and write the viewer manifest.

    python src/build_sequence.py --frames output/sequence/ --out viewer/manifest.json

Real and synthesized frames are ordered by capture angle and tagged, so the
viewer can show either the full interpolated sequence or just the captured
frames (the object-movie baseline) without rebuilding anything.

Angles are only written if --angular-step is supplied, because the capture step
is something you measured in the field -- this script will not guess it. Without
it, frames carry angle: null and the viewer shows an index instead.

Two files are written next to each other:

    manifest.json   canonical output
    manifest.js     same data as `window.SALA_MANIFEST = {...}`

The .js copy exists because browsers block fetch() of local .json over file://,
and CLAUDE.md requires the viewer to open straight from file:// with no server.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys

IMAGE_EXTS = (".jpg", ".jpeg", ".png")
# frame_0007.jpg  or  frame_0007_i2.jpg
PATTERN = re.compile(r"^frame_(\d+)(?:_i(\d+))?\.(?:jpg|jpeg|png)$", re.IGNORECASE)


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--frames", required=True, help="sequence directory from interpolate.py")
    p.add_argument("--out", required=True, help="output manifest path (.json)")
    p.add_argument("--angular-step", type=float, default=None,
                   help="degrees between CAPTURED frames, as measured during capture")
    p.add_argument("--start-angle", type=float, default=0.0, help="angle of the first captured frame")
    args = p.parse_args()

    if not os.path.isdir(args.frames):
        sys.exit(f"No such directory: {args.frames}")

    # Prefer the t values interpolate.py recorded; fall back to even spacing.
    recorded = {}
    n_between = None
    meta_path = os.path.join(args.frames, "interpolation.json")
    if os.path.isfile(meta_path):
        with open(meta_path) as fh:
            meta = json.load(fh)
        n_between = meta.get("n_between")
        recorded = {r["file"]: r for r in meta.get("frames", [])}
    else:
        print(f"note: no interpolation.json in {args.frames}; inferring spacing from filenames")

    entries = []
    for name in os.listdir(args.frames):
        if not name.lower().endswith(IMAGE_EXTS):
            continue
        m = PATTERN.match(name)
        if not m:
            print(f"  skipped unrecognised filename: {name}")
            continue
        base = int(m.group(1))
        sub = int(m.group(2)) if m.group(2) else 0
        entries.append((base, sub, name))

    if not entries:
        sys.exit(f"No frames matching frame_NNNN[_iK].jpg in {args.frames}")
    entries.sort()

    if n_between is None:
        n_between = max(sub for _, sub, _ in entries)

    out_dir = os.path.dirname(os.path.abspath(args.out))
    os.makedirs(out_dir, exist_ok=True)
    rel_root = os.path.relpath(os.path.abspath(args.frames), out_dir).replace(os.sep, "/")

    frames = []
    for i, (base, sub, name) in enumerate(entries):
        rec = recorded.get(name)
        if rec is not None:
            t = rec["t"]
            real = rec["kind"] == "real"
        else:
            t = sub / (n_between + 1) if n_between else 0.0
            real = sub == 0
        angle = None
        if args.angular_step is not None:
            angle = round(args.start_angle + (base + t) * args.angular_step, 4)
        frames.append({
            "index": i,
            "file": f"{rel_root}/{name}",
            "real": real,
            "captured_index": base,
            "t": round(t, 6),
            "angle_deg": angle,
        })

    n_real = sum(1 for f in frames if f["real"])
    manifest = {
        "generated_by": "build_sequence.py",
        "sequence_dir": args.frames,
        "n_frames": len(frames),
        "n_captured": n_real,
        "n_synthesized": len(frames) - n_real,
        "n_between": n_between,
        # The pavilion sits on the lake edge, so the capture is a partial arc.
        # The viewer must clamp at both ends rather than looping around.
        "wraparound": False,
        "angular_step_deg": args.angular_step,
        "start_angle_deg": args.start_angle,
        "frames": frames,
    }

    with open(args.out, "w") as fh:
        json.dump(manifest, fh, indent=2)

    js_path = os.path.splitext(args.out)[0] + ".js"
    with open(js_path, "w") as fh:
        fh.write("// Generated by build_sequence.py -- do not edit.\n")
        fh.write("// Loaded via <script> so the viewer works over file:// too.\n")
        fh.write("window.SALA_MANIFEST = ")
        json.dump(manifest, fh, indent=2)
        fh.write(";\n")

    print(f"{len(frames)} frames ({n_real} captured + {len(frames) - n_real} synthesized)")
    print(f"  {args.out}")
    print(f"  {js_path}")
    if args.angular_step is None:
        print("  angles: null (pass --angular-step to record the measured capture step)")
    else:
        print(f"  angles: {frames[0]['angle_deg']} .. {frames[-1]['angle_deg']} deg")


if __name__ == "__main__":
    main()
